# Generated by Django 5.2.10 on 2026-02-07 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_equiposeccion_equipomiembro'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carcon_video_file', models.FileField(blank=True, help_text='Sube un video (mp4/webm). Si existe, se usa este en lugar de la URL.', null=True, upload_to='videos/')),
                ('carcon_video_url', models.URLField(blank=True, help_text='URL del video. Para YouTube puedes pegar link normal o embed.')),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Inicio',
                'verbose_name_plural': 'Configuración de Inicio',
            },
        ),
    ]
