# Generated by Django 5.2.9 on 2026-03-14 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0004_homepageconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='modelo_3d',
            field=models.FileField(blank=True, help_text='Archivo GLB o GLTF del modelo 3D. Se mostrará como visor interactivo en la página del proyecto.', null=True, upload_to='modelos3d/'),
        ),
    ]
