# Generated by Django 5.2.9 on 2026-02-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_proyectoimagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoSeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_grupal', models.ImageField(blank=True, null=True, upload_to='equipo/')),
                ('activo', models.BooleanField(default=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sección Equipo',
                'verbose_name_plural': 'Sección Equipo',
            },
        ),
        migrations.CreateModel(
            name='EquipoMiembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('rol', models.CharField(choices=[('arquitecto', 'Arquitecto'), ('colaborador', 'Colaborador')], max_length=20)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='equipo/')),
                ('orden', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Miembro del equipo',
                'verbose_name_plural': 'Miembros del equipo',
                'ordering': ['rol', 'orden', 'id'],
            },
        ),
    ]
